// TEMPORARY DATA

export let role = "student";

export const teachersData = [
  {
    id: 1,
    teacherId: "BPIT123456",
    name: "Rajesh Sharma",
    email: "rajesh.sharma@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543210",
    subjects: ["Math-I", "DM"],
    classes: ["CSE 1st", "IT 2nd"],
    address: "BPIT College, New Delhi",
  },
  {
    id: 2,
    teacherId: "BPIT123457",
    name: "Priya Verma",
    email: "priya.verma@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543211",
    subjects: ["Phy", "EM"],
    classes: ["1st Year"],
    address: "BPIT College, New Delhi",
  },
  {
    id: 3,
    teacherId: "BPIT123458",
    name: "Amitabh Desai",
    email: "amitabh.desai@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543212",
    subjects: ["DSA", "Algo"],
    classes: ["CSE 2nd", "IT 3rd"],
    address: "BPIT College, New Delhi",
  },
  {
    id: 4,
    teacherId: "BPIT123459",
    name: "Suresh Nair",
    email: "suresh.nair@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543213",
    subjects: ["DBMS", "SE"],
    classes: ["IT 2nd", "CSE 3rd"],
    address: "BPIT College, New Delhi",
  },
  {
    id: 5,
    teacherId: "BPIT123460",
    name: "Neha Mehta",
    email: "neha.mehta@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543214",
    subjects: ["OS", "CN"],
    classes: ["CSE 3rd", "IT 4th"],
    address: "BPIT College, New Delhi",
  },
  {
    id: 6,
    teacherId: "BPIT123461",
    name: "Ravi Kumar",
    email: "ravi.kumar@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543215",
    subjects: ["ML", "AI"],
    classes: ["CSE 4th", "IT 4th"],
    address: "BPIT College, New Delhi",
  },
  {
    id: 7,
    teacherId: "BPIT123462",
    name: "Anita Gupta",
    email: "anita.gupta@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543216",
    subjects: ["DLD", "MP"],
    classes: ["ECE 2nd", "CSE 2nd"],
    address: "BPIT College, New Delhi",
  },
  {
    id: 8,
    teacherId: "BPIT123463",
    name: "Rohan Das",
    email: "rohan.das@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543217",
    subjects: ["CD", "TOC"],
    classes: ["CSE 3rd", "IT 3rd"],
    address: "BPIT College, New Delhi",
  },
  {
    id: 9,
    teacherId: "BPIT123464",
    name: "Pooja Iyer",
    email: "pooja.iyer@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543218",
    subjects: ["CyberSec", "CC"],
    classes: ["IT 4th", "CSE 4th"],
    address: "BPIT College, New Delhi",
  },
  {
    id: 10,
    teacherId: "BPIT123465",
    name: "Arun Joshi",
    email: "arun.joshi@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543219",
    subjects: ["ST", "DevOps"],
    classes: ["IT 3rd", "CSE 4th"],
    address: "BPIT College, New Delhi",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "BPIT202501",
    name: "Aman Verma",
    email: "aman.verma@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543210",
    grade: "1st",
    class: "CSE",
    address: "BPIT College, New Delhi",
  },
  {
    id: 2,
    studentId: "BPIT202502",
    name: "Neha Sharma",
    email: "neha.sharma@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543211",
    grade: "2nd",
    class: "IT",
    address: "BPIT College, New Delhi",
  },
  {
    id: 3,
    studentId: "BPIT202503",
    name: "Rohan Gupta",
    email: "rohan.gupta@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543212",
    grade: "3rd",
    class: "ECE",
    address: "BPIT College, New Delhi",
  },
  {
    id: 4,
    studentId: "BPIT202504",
    name: "Sneha Iyer",
    email: "sneha.iyer@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543213",
    grade: "1st",
    class: "IT",
    address: "BPIT College, New Delhi",
  },
  {
    id: 5,
    studentId: "BPIT202505",
    name: "Varun Joshi",
    email: "varun.joshi@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543214",
    grade: "4th",
    class: "CSE",
    address: "BPIT College, New Delhi",
  },
  {
    id: 6,
    studentId: "BPIT202506",
    name: "Pooja Mehta",
    email: "pooja.mehta@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543215",
    grade: "2nd",
    class: "ECE",
    address: "BPIT College, New Delhi",
  },
  {
    id: 7,
    studentId: "BPIT202507",
    name: "Rahul Desai",
    email: "rahul.desai@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543216",
    grade: "3rd",
    class: "CSE",
    address: "BPIT College, New Delhi",
  },
  {
    id: 8,
    studentId: "BPIT202508",
    name: "Ananya Singh",
    email: "ananya.singh@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543217",
    grade: "4th",
    class: "IT",
    address: "BPIT College, New Delhi",
  },
  {
    id: 9,
    studentId: "BPIT202509",
    name: "Vikram Nair",
    email: "vikram.nair@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543218",
    grade: "1st",
    class: "ECE",
    address: "BPIT College, New Delhi",
  },
  {
    id: 10,
    studentId: "BPIT202510",
    name: "Simran Kaur",
    email: "simran.kaur@bpit.ac.in",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543219",
    grade: "3rd",
    class: "IT",
    address: "BPIT College, New Delhi",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Rajesh Verma",
    students: ["Aman Verma"],
    email: "rajesh.verma@example.com",
    phone: "9876543210",
    address: "Dwarka, New Delhi",
  },
  {
    id: 2,
    name: "Suman Sharma",
    students: ["Neha Sharma"],
    email: "suman.sharma@example.com",
    phone: "9876543211",
    address: "Lajpat Nagar, New Delhi",
  },
  {
    id: 3,
    name: "Prakash Gupta",
    students: ["Rohan Gupta"],
    email: "prakash.gupta@example.com",
    phone: "9876543212",
    address: "Rohini, New Delhi",
  },
  {
    id: 4,
    name: "Vimala Iyer",
    students: ["Sneha Iyer"],
    email: "vimala.iyer@example.com",
    phone: "9876543213",
    address: "Karol Bagh, New Delhi",
  },
  {
    id: 5,
    name: "Suresh Joshi",
    students: ["Varun Joshi"],
    email: "suresh.joshi@example.com",
    phone: "9876543214",
    address: "Saket, New Delhi",
  },
  {
    id: 6,
    name: "Meena Mehta",
    students: ["Pooja Mehta"],
    email: "meena.mehta@example.com",
    phone: "9876543215",
    address: "Janakpuri, New Delhi",
  },
  {
    id: 7,
    name: "Anil Desai",
    students: ["Rahul Desai"],
    email: "anil.desai@example.com",
    phone: "9876543216",
    address: "Pitampura, New Delhi",
  },
  {
    id: 8,
    name: "Rakesh Singh",
    students: ["Ananya Singh"],
    email: "rakesh.singh@example.com",
    phone: "9876543217",
    address: "Vasant Kunj, New Delhi",
  },
  {
    id: 9,
    name: "Sunil Nair",
    students: ["Vikram Nair"],
    email: "sunil.nair@example.com",
    phone: "9876543218",
    address: "Connaught Place, New Delhi",
  },
  {
    id: 10,
    name: "Baljeet Kaur",
    students: ["Simran Kaur"],
    email: "baljeet.kaur@example.com",
    phone: "9876543219",
    address: "Chandni Chowk, Old Delhi",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math-I",
    teachers: ["Rajesh Sharma", "Neha Mehta"],
  },
  {
    id: 2,
    name: "Physics",
    teachers: ["Priya Verma", "Ravi Kumar"],
  },
  {
    id: 3,
    name: "Chemistry",
    teachers: ["Amitabh Desai", "Suresh Nair"],
  },
  {
    id: 4,
    name: "DSA",
    teachers: ["Rahul Desai", "Anita Gupta"],
  },
  {
    id: 5,
    name: "DBMS",
    teachers: ["Suresh Nair", "Rohan Das"],
  },
  {
    id: 6,
    name: "OS",
    teachers: ["Neha Mehta", "Vikram Nair"],
  },
  {
    id: 7,
    name: "CN",
    teachers: ["Pooja Iyer", "Baljeet Kaur"],
  },
  {
    id: 8,
    name: "AI",
    teachers: ["Ravi Kumar", "Ananya Singh"],
  },
  {
    id: 9,
    name: "ML",
    teachers: ["Anil Desai", "Varun Joshi"],
  },
  {
    id: 10,
    name: "CyberSec",
    teachers: ["Pooja Iyer", "Simran Kaur"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "CSE 1st",
    capacity: 60,
    grade: "1st",
    supervisor: "Rajesh Sharma",
  },
  {
    id: 2,
    name: "IT 1st",
    capacity: 55,
    grade: "1st",
    supervisor: "Priya Verma",
  },
  {
    id: 3,
    name: "ECE 1st",
    capacity: 50,
    grade: "1st",
    supervisor: "Ravi Kumar",
  },
  {
    id: 4,
    name: "CSE 2nd",
    capacity: 60,
    grade: "2nd",
    supervisor: "Suresh Nair",
  },
  {
    id: 5,
    name: "IT 2nd",
    capacity: 55,
    grade: "2nd",
    supervisor: "Neha Mehta",
  },
  {
    id: 6,
    name: "ECE 2nd",
    capacity: 50,
    grade: "2nd",
    supervisor: "Rohan Das",
  },
  {
    id: 7,
    name: "CSE 3rd",
    capacity: 60,
    grade: "3rd",
    supervisor: "Anil Desai",
  },
  {
    id: 8,
    name: "IT 3rd",
    capacity: 55,
    grade: "3rd",
    supervisor: "Pooja Iyer",
  },
  {
    id: 9,
    name: "ECE 3rd",
    capacity: 50,
    grade: "3rd",
    supervisor: "Baljeet Kaur",
  },
  {
    id: 10,
    name: "CSE 4th",
    capacity: 60,
    grade: "4th",
    supervisor: "Rahul Desai",
  },
  {
    id: 11,
    name: "IT 4th",
    capacity: 55,
    grade: "4th",
    supervisor: "Varun Joshi",
  },
  {
    id: 12,
    name: "ECE 4th",
    capacity: 50,
    grade: "4th",
    supervisor: "Simran Kaur",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math-I",
    class: "CSE 1st",
    teacher: "Rajesh Sharma",
  },
  {
    id: 2,
    subject: "Physics",
    class: "IT 1st",
    teacher: "Priya Verma",
  },
  {
    id: 3,
    subject: "Chemistry",
    class: "ECE 1st",
    teacher: "Ravi Kumar",
  },
  {
    id: 4,
    subject: "DSA",
    class: "CSE 2nd",
    teacher: "Rahul Desai",
  },
  {
    id: 5,
    subject: "DBMS",
    class: "IT 2nd",
    teacher: "Suresh Nair",
  },
  {
    id: 6,
    subject: "OS",
    class: "ECE 2nd",
    teacher: "Neha Mehta",
  },
  {
    id: 7,
    subject: "CN",
    class: "CSE 3rd",
    teacher: "Pooja Iyer",
  },
  {
    id: 8,
    subject: "AI",
    class: "IT 3rd",
    teacher: "Ravi Kumar",
  },
  {
    id: 9,
    subject: "ML",
    class: "ECE 3rd",
    teacher: "Anil Desai",
  },
  {
    id: 10,
    subject: "CyberSec",
    class: "CSE 4th",
    teacher: "Pooja Iyer",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math-I",
    class: "CSE 1st",
    teacher: "Rajesh Sharma",
    date: "2025-05-10",
  },
  {
    id: 2,
    subject: "Physics",
    class: "IT 1st",
    teacher: "Priya Verma",
    date: "2025-05-12",
  },
  {
    id: 3,
    subject: "Chemistry",
    class: "ECE 1st",
    teacher: "Ravi Kumar",
    date: "2025-05-14",
  },
  {
    id: 4,
    subject: "DSA",
    class: "CSE 2nd",
    teacher: "Rahul Desai",
    date: "2025-05-16",
  },
  {
    id: 5,
    subject: "DBMS",
    class: "IT 2nd",
    teacher: "Suresh Nair",
    date: "2025-05-18",
  },
  {
    id: 6,
    subject: "OS",
    class: "ECE 2nd",
    teacher: "Neha Mehta",
    date: "2025-05-20",
  },
  {
    id: 7,
    subject: "CN",
    class: "CSE 3rd",
    teacher: "Pooja Iyer",
    date: "2025-05-22",
  },
  {
    id: 8,
    subject: "AI",
    class: "IT 3rd",
    teacher: "Ravi Kumar",
    date: "2025-05-24",
  },
  {
    id: 9,
    subject: "ML",
    class: "ECE 3rd",
    teacher: "Anil Desai",
    date: "2025-05-26",
  },
  {
    id: 10,
    subject: "CyberSec",
    class: "CSE 4th",
    teacher: "Pooja Iyer",
    date: "2025-05-28",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math-I",
    class: "CSE 1st",
    teacher: "Rajesh Sharma",
    dueDate: "2025-03-05",
  },
  {
    id: 2,
    subject: "Physics",
    class: "IT 1st",
    teacher: "Priya Verma",
    dueDate: "2025-03-07",
  },
  {
    id: 3,
    subject: "Chemistry",
    class: "ECE 1st",
    teacher: "Ravi Kumar",
    dueDate: "2025-03-09",
  },
  {
    id: 4,
    subject: "DSA",
    class: "CSE 2nd",
    teacher: "Rahul Desai",
    dueDate: "2025-03-11",
  },
  {
    id: 5,
    subject: "DBMS",
    class: "IT 2nd",
    teacher: "Suresh Nair",
    dueDate: "2025-03-13",
  },
  {
    id: 6,
    subject: "OS",
    class: "ECE 2nd",
    teacher: "Neha Mehta",
    dueDate: "2025-03-15",
  },
  {
    id: 7,
    subject: "CN",
    class: "CSE 3rd",
    teacher: "Pooja Iyer",
    dueDate: "2025-03-17",
  },
  {
    id: 8,
    subject: "AI",
    class: "IT 3rd",
    teacher: "Ravi Kumar",
    dueDate: "2025-03-19",
  },
  {
    id: 9,
    subject: "ML",
    class: "ECE 3rd",
    teacher: "Anil Desai",
    dueDate: "2025-03-21",
  },
  {
    id: 10,
    subject: "CyberSec",
    class: "CSE 4th",
    teacher: "Pooja Iyer",
    dueDate: "2025-03-23",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math-I",
    class: "CSE 1st",
    teacher: "Rajesh Sharma",
    student: "Aman Verma",
    date: "2025-06-10",
    type: "exam",
    score: 88,
  },
  {
    id: 2,
    subject: "Physics",
    class: "IT 1st",
    teacher: "Priya Verma",
    student: "Neha Sharma",
    date: "2025-06-12",
    type: "exam",
    score: 85,
  },
  {
    id: 3,
    subject: "Chemistry",
    class: "ECE 1st",
    teacher: "Ravi Kumar",
    student: "Rohan Gupta",
    date: "2025-06-14",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "DSA",
    class: "CSE 2nd",
    teacher: "Rahul Desai",
    student: "Sneha Iyer",
    date: "2025-06-16",
    type: "exam",
    score: 92,
  },
  {
    id: 5,
    subject: "DBMS",
    class: "IT 2nd",
    teacher: "Suresh Nair",
    student: "Varun Joshi",
    date: "2025-06-18",
    type: "exam",
    score: 87,
  },
  {
    id: 6,
    subject: "OS",
    class: "ECE 2nd",
    teacher: "Neha Mehta",
    student: "Pooja Mehta",
    date: "2025-06-20",
    type: "exam",
    score: 89,
  },
  {
    id: 7,
    subject: "CN",
    class: "CSE 3rd",
    teacher: "Pooja Iyer",
    student: "Rahul Desai",
    date: "2025-06-22",
    type: "exam",
    score: 91,
  },
  {
    id: 8,
    subject: "AI",
    class: "IT 3rd",
    teacher: "Ravi Kumar",
    student: "Ananya Singh",
    date: "2025-06-24",
    type: "exam",
    score: 86,
  },
  {
    id: 9,
    subject: "ML",
    class: "ECE 3rd",
    teacher: "Anil Desai",
    student: "Vikram Nair",
    date: "2025-06-26",
    type: "exam",
    score: 93,
  },
  {
    id: 10,
    subject: "CyberSec",
    class: "CSE 4th",
    teacher: "Pooja Iyer",
    student: "Simran Kaur",
    date: "2025-06-28",
    type: "exam",
    score: 88,
  },
];


export const eventsData = [
  {
    id: 1,
    title: "Tech Fest",
    class: "CSE 1st",
    date: "2025-03-15",
    startTime: "10:00",
    endTime: "17:00",
  },
  {
    id: 2,
    title: "AI Workshop",
    class: "IT 2nd",
    date: "2025-03-18",
    startTime: "11:00",
    endTime: "15:00",
  },
  {
    id: 3,
    title: "Hackathon",
    class: "ECE 3rd",
    date: "2025-03-22",
    startTime: "09:00",
    endTime: "21:00",
  },
  {
    id: 4,
    title: "Industrial Visit",
    class: "CSE 2nd",
    date: "2025-04-05",
    startTime: "08:00",
    endTime: "18:00",
  },
  {
    id: 5,
    title: "Coding Competition",
    class: "IT 3rd",
    date: "2025-04-10",
    startTime: "10:00",
    endTime: "14:00",
  },
  {
    id: 6,
    title: "Seminar on Cyber Security",
    class: "ECE 4th",
    date: "2025-04-15",
    startTime: "12:00",
    endTime: "16:00",
  },
  {
    id: 7,
    title: "Internship Fair",
    class: "CSE 3rd",
    date: "2025-04-20",
    startTime: "09:00",
    endTime: "17:00",
  },
  {
    id: 8,
    title: "Guest Lecture on Cloud Computing",
    class: "IT 4th",
    date: "2025-04-25",
    startTime: "10:30",
    endTime: "13:30",
  },
  {
    id: 9,
    title: "Project Expo",
    class: "ECE 3rd",
    date: "2025-05-05",
    startTime: "11:00",
    endTime: "16:00",
  },
  {
    id: 10,
    title: "Placement Drive",
    class: "CSE 4th",
    date: "2025-05-10",
    startTime: "09:00",
    endTime: "18:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "Mid-Semester Exam Schedule Released",
    class: "CSE 1st",
    date: "2025-03-10",
  },
  {
    id: 2,
    title: "AI Workshop Registration Open",
    class: "IT 2nd",
    date: "2025-03-15",
  },
  {
    id: 3,
    title: "DSA Assignment Submission Deadline",
    class: "CSE 2nd",
    date: "2025-03-20",
  },
  {
    id: 4,
    title: "Industrial Visit Confirmation",
    class: "ECE 3rd",
    date: "2025-03-25",
  },
  {
    id: 5,
    title: "DBMS Practical Exam Date Announced",
    class: "IT 3rd",
    date: "2025-03-30",
  },
  {
    id: 6,
    title: "OS Lab Submission Reminder",
    class: "ECE 2nd",
    date: "2025-04-05",
  },
  {
    id: 7,
    title: "Cyber Security Seminar Details",
    class: "CSE 4th",
    date: "2025-04-10",
  },
  {
    id: 8,
    title: "Project Expo Participation Open",
    class: "ECE 3rd",
    date: "2025-04-15",
  },
  {
    id: 9,
    title: "Placement Drive Guidelines",
    class: "IT 4th",
    date: "2025-04-20",
  },
  {
    id: 10,
    title: "Final Year Project Presentation Schedule",
    class: "CSE 4th",
    date: "2025-04-25",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math-I",
    allDay: false,
    start: new Date(2025, 6, 14, 8, 0), // July 14, 2025
    end: new Date(2025, 6, 14, 8, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 6, 14, 9, 0),
    end: new Date(2025, 6, 14, 9, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 6, 14, 10, 0),
    end: new Date(2025, 6, 14, 10, 45),
  },
  {
    title: "DSA",
    allDay: false,
    start: new Date(2025, 6, 15, 8, 0), // July 15, 2025
    end: new Date(2025, 6, 15, 8, 45),
  },
  {
    title: "DBMS",
    allDay: false,
    start: new Date(2025, 6, 15, 9, 0),
    end: new Date(2025, 6, 15, 9, 45),
  },
  {
    title: "OS",
    allDay: false,
    start: new Date(2025, 6, 15, 10, 0),
    end: new Date(2025, 6, 15, 10, 45),
  },
  {
    title: "CN",
    allDay: false,
    start: new Date(2025, 6, 16, 8, 0), // July 16, 2025
    end: new Date(2025, 6, 16, 8, 45),
  },
  {
    title: "AI",
    allDay: false,
    start: new Date(2025, 6, 16, 9, 0),
    end: new Date(2025, 6, 16, 9, 45),
  },
  {
    title: "ML",
    allDay: false,
    start: new Date(2025, 6, 16, 10, 0),
    end: new Date(2025, 6, 16, 10, 45),
  },
  {
    title: "CyberSec",
    allDay: false,
    start: new Date(2025, 6, 17, 8, 0), // July 17, 2025
    end: new Date(2025, 6, 17, 8, 45),
  },
  {
    title: "Cloud Computing",
    allDay: false,
    start: new Date(2025, 6, 17, 9, 0),
    end: new Date(2025, 6, 17, 9, 45),
  },
  {
    title: "Project Lab",
    allDay: false,
    start: new Date(2025, 6, 17, 10, 0),
    end: new Date(2025, 6, 17, 11, 45),
  },
  {
    title: "Technical Seminar",
    allDay: false,
    start: new Date(2025, 6, 18, 8, 0), // July 18, 2025
    end: new Date(2025, 6, 18, 10, 0),
  },
  {
    title: "Coding Competition",
    allDay: false,
    start: new Date(2025, 6, 18, 11, 0),
    end: new Date(2025, 6, 18, 13, 0),
  },
  {
    title: "Internship Fair",
    allDay: false,
    start: new Date(2025, 6, 19, 9, 0), // July 19, 2025
    end: new Date(2025, 6, 19, 15, 0),
  },
  {
    title: "Hackathon",
    allDay: false,
    start: new Date(2025, 6, 20, 8, 0), // July 20, 2025
    end: new Date(2025, 6, 20, 20, 0),
  },
];
